---
authorize:    false
dir_max_len:  95
dir_lang:     english
save_dir:     ./doujinshi
user_agent:   Windows Mozilla
use_http_proxy:   true
http_proxy_host:  127.0.0.1
http_proxy_port:  12301
first_language:   english